# Generated by Django 3.1.5 on 2021-01-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weeklyexpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datee', models.CharField(db_column='Datee', max_length=5)),
                ('ccord', models.CharField(db_column='CCorD', max_length=6)),
                ('amountspent', models.CharField(db_column='AmountSpent', max_length=6)),
                ('category', models.CharField(db_column='Category', max_length=13)),
            ],
            options={
                'db_table': 'weeklyexpenses',
                'managed': True,
            },
        ),
    ]
