# Generated by Django 3.1.5 on 2021-01-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyexpenses',
            name='amountspent',
            field=models.CharField(db_column='AmountSpent', max_length=15),
        ),
        migrations.AlterField(
            model_name='weeklyexpenses',
            name='ccord',
            field=models.CharField(db_column='CCorD', max_length=10),
        ),
        migrations.AlterField(
            model_name='weeklyexpenses',
            name='datee',
            field=models.CharField(db_column='Datee', max_length=15),
        ),
    ]
